### ISSUE TITLE
ERR "float unrepresentable in integer range"

### ISSUE THREAD

**Issue by datdo85** [Rillke/flac.js#12] opened 2018-10-28 08:58 UTC
Hello,

Getting an error while trying to encode *.wav data to flac. 
I try convert it with your demo. https://rawgit.com/Rillke/flac.js/master/iframe.html
Can you help me resolve it?
[convert_files.zip](https://github.com/Rillke/flac.js/files/2522610/convert_files.zip)

**Comment by Rillke** [comment] 2018-11-29 01:15
flac seems to do some [float-to-integer](https://kripken.github.io/emscripten-site/docs/compiling/WebAssembly.html#binaryen-codegen-options) conversion that fails. That is why the wasm build may fail. Fixed with 1c530b5333a85d3d9fe5c4d6384169ae6da16e7c. Duplicate of #11 - error message generated by different user agent.
Thanks for the report.

**Closed as completed by Rillke** 2018-11-29 01:15 UTC
Labels: bug, wasm
